# Generated by Django 4.2.5 on 2023-11-16 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='Departments',
        ),
        migrations.RenameField(
            model_name='departments',
            old_name='dep_description',
            new_name='dept_description',
        ),
        migrations.RenameField(
            model_name='departments',
            old_name='dep_name',
            new_name='dept_name',
        ),
        migrations.RenameField(
            model_name='doctors',
            old_name='dep_name',
            new_name='dept_name',
        ),
    ]
