# Generated by Django 4.2.5 on 2023-11-16 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_department_departments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departments',
            old_name='dept_description',
            new_name='dep_description',
        ),
        migrations.RenameField(
            model_name='departments',
            old_name='dept_name',
            new_name='dep_name',
        ),
        migrations.RenameField(
            model_name='doctors',
            old_name='dept_name',
            new_name='dep_name',
        ),
    ]
